<?php

namespace Proxies\__CG__\SNT\SoultanaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Bien extends \SNT\SoultanaBundle\Entity\Bien implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'idBien', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'nomBien', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'prixLocation', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'surface', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'nbreChambre', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'nbreEtage', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'nbreSalon', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'nbreSalleBain', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'balcon', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'meuble', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'parking', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'terasse', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'description', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'disponibilite', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'idProprietaire', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'idParent', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'idTypeBien', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'idQuartier'];
        }

        return ['__isInitialized__', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'idBien', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'nomBien', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'prixLocation', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'surface', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'nbreChambre', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'nbreEtage', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'nbreSalon', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'nbreSalleBain', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'balcon', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'meuble', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'parking', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'terasse', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'description', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'disponibilite', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'idProprietaire', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'idParent', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'idTypeBien', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Bien' . "\0" . 'idQuartier'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Bien $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdBien()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdBien();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdBien', []);

        return parent::getIdBien();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomBien($nomBien)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomBien', [$nomBien]);

        return parent::setNomBien($nomBien);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomBien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomBien', []);

        return parent::getNomBien();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixLocation($prixLocation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixLocation', [$prixLocation]);

        return parent::setPrixLocation($prixLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixLocation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixLocation', []);

        return parent::getPrixLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurface($surface)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurface', [$surface]);

        return parent::setSurface($surface);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurface()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurface', []);

        return parent::getSurface();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbreChambre($nbreChambre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbreChambre', [$nbreChambre]);

        return parent::setNbreChambre($nbreChambre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbreChambre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbreChambre', []);

        return parent::getNbreChambre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbreEtage($nbreEtage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbreEtage', [$nbreEtage]);

        return parent::setNbreEtage($nbreEtage);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbreEtage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbreEtage', []);

        return parent::getNbreEtage();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbreSalon($nbreSalon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbreSalon', [$nbreSalon]);

        return parent::setNbreSalon($nbreSalon);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbreSalon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbreSalon', []);

        return parent::getNbreSalon();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbreSalleBain($nbreSalleBain)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbreSalleBain', [$nbreSalleBain]);

        return parent::setNbreSalleBain($nbreSalleBain);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbreSalleBain()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbreSalleBain', []);

        return parent::getNbreSalleBain();
    }

    /**
     * {@inheritDoc}
     */
    public function setBalcon($balcon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBalcon', [$balcon]);

        return parent::setBalcon($balcon);
    }

    /**
     * {@inheritDoc}
     */
    public function getBalcon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalcon', []);

        return parent::getBalcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setMeuble($meuble)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMeuble', [$meuble]);

        return parent::setMeuble($meuble);
    }

    /**
     * {@inheritDoc}
     */
    public function getMeuble()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeuble', []);

        return parent::getMeuble();
    }

    /**
     * {@inheritDoc}
     */
    public function setParking($parking)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParking', [$parking]);

        return parent::setParking($parking);
    }

    /**
     * {@inheritDoc}
     */
    public function getParking()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParking', []);

        return parent::getParking();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerasse($terasse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerasse', [$terasse]);

        return parent::setTerasse($terasse);
    }

    /**
     * {@inheritDoc}
     */
    public function getTerasse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerasse', []);

        return parent::getTerasse();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisponibilite($disponibilite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisponibilite', [$disponibilite]);

        return parent::setDisponibilite($disponibilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisponibilite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisponibilite', []);

        return parent::getDisponibilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProprietaire(\SNT\SoultanaBundle\Entity\Proprietaire $idProprietaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProprietaire', [$idProprietaire]);

        return parent::setIdProprietaire($idProprietaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdProprietaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProprietaire', []);

        return parent::getIdProprietaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdParent(\SNT\SoultanaBundle\Entity\Bien $idParent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdParent', [$idParent]);

        return parent::setIdParent($idParent);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdParent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdParent', []);

        return parent::getIdParent();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTypeBien(\SNT\SoultanaBundle\Entity\TypeBien $idTypeBien = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTypeBien', [$idTypeBien]);

        return parent::setIdTypeBien($idTypeBien);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTypeBien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTypeBien', []);

        return parent::getIdTypeBien();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdQuartier(\SNT\SoultanaBundle\Entity\Quartier $idQuartier = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdQuartier', [$idQuartier]);

        return parent::setIdQuartier($idQuartier);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdQuartier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdQuartier', []);

        return parent::getIdQuartier();
    }

}
