<?php

namespace Proxies\__CG__\SNT\SoultanaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Proprietaire extends \SNT\SoultanaBundle\Entity\Proprietaire implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Proprietaire' . "\0" . 'idProprietaire', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Proprietaire' . "\0" . 'numPiece', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Proprietaire' . "\0" . 'nomComplet', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Proprietaire' . "\0" . 'adresse', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Proprietaire' . "\0" . 'tel', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Proprietaire' . "\0" . 'email', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Proprietaire' . "\0" . 'codeBanque'];
        }

        return ['__isInitialized__', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Proprietaire' . "\0" . 'idProprietaire', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Proprietaire' . "\0" . 'numPiece', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Proprietaire' . "\0" . 'nomComplet', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Proprietaire' . "\0" . 'adresse', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Proprietaire' . "\0" . 'tel', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Proprietaire' . "\0" . 'email', '' . "\0" . 'SNT\\SoultanaBundle\\Entity\\Proprietaire' . "\0" . 'codeBanque'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Proprietaire $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdProprietaire()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdProprietaire();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProprietaire', []);

        return parent::getIdProprietaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumPiece($numPiece)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumPiece', [$numPiece]);

        return parent::setNumPiece($numPiece);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumPiece()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumPiece', []);

        return parent::getNumPiece();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomComplet($nomComplet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomComplet', [$nomComplet]);

        return parent::setNomComplet($nomComplet);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomComplet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomComplet', []);

        return parent::getNomComplet();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setTel($tel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTel', [$tel]);

        return parent::setTel($tel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTel', []);

        return parent::getTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeBanque($codeBanque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeBanque', [$codeBanque]);

        return parent::setCodeBanque($codeBanque);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeBanque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeBanque', []);

        return parent::getCodeBanque();
    }

}
